/**
 * DEMO coupons — used until Laravel exposes /admin/coupons and /shop/coupons/apply.
 * Share these codes with QA: SAVE10, FLAT20, WELCOME15, FREESHIP
 */
import type { Coupon } from '../types/coupon';

export const DUMMY_COUPONS: Coupon[] = [
  {
    id: '1',
    code: 'SAVE10',
    title: '10% off',
    description: '10% off orders over AED 50 (max AED 30 off). All store products.',
    discount_type: 'percentage',
    discount_value: 10,
    min_order_amount: 50,
    max_discount_amount: 30,
    is_active: true,
    usage_limit_per_user: 3,
    applies_to: 'all',
    catalog_scope: 'products',
    category_ids: [],
    service_ids: [],
  },
  {
    id: '2',
    code: 'FLAT20',
    title: 'AED 20 off',
    description: 'Fixed AED 20 discount on orders over AED 100.',
    discount_type: 'fixed_amount',
    discount_value: 20,
    min_order_amount: 100,
    is_active: true,
    applies_to: 'all',
    catalog_scope: 'products',
    category_ids: [],
    service_ids: [],
  },
  {
    id: '3',
    code: 'WELCOME15',
    title: 'Welcome 15%',
    description: '15% off first-style promo (min AED 80, max AED 50 off).',
    discount_type: 'percentage',
    discount_value: 15,
    min_order_amount: 80,
    max_discount_amount: 50,
    is_active: true,
    applies_to: 'all',
    catalog_scope: 'products',
    category_ids: [],
    service_ids: [],
  },
  {
    id: '4',
    code: 'FREESHIP',
    title: 'Free shipping',
    description: 'No delivery fee on orders over AED 75.',
    discount_type: 'free_shipping',
    discount_value: 0,
    min_order_amount: 75,
    is_active: true,
    applies_to: 'all',
    catalog_scope: 'products',
    category_ids: [],
    service_ids: [],
  },
  {
    id: '6',
    code: 'DEMO5',
    title: 'AED 5 off (small orders)',
    description: 'Demo: works on any cart — min order AED 0.',
    discount_type: 'fixed_amount',
    discount_value: 5,
    min_order_amount: 0,
    is_active: true,
    applies_to: 'all',
    catalog_scope: 'products',
    category_ids: [],
    service_ids: [],
  },
  {
    id: '7',
    code: 'CAT10',
    title: '10% category demo',
    description: 'Demo: only when cart has products from category id 1.',
    discount_type: 'percentage',
    discount_value: 10,
    min_order_amount: 0,
    max_discount_amount: 20,
    is_active: true,
    applies_to: 'categories',
    catalog_scope: 'products',
    category_ids: [1],
    service_ids: [],
  },
  {
    id: '5',
    code: 'EXPIRED',
    title: 'Expired (demo)',
    description: 'Inactive — should fail when applied.',
    discount_type: 'percentage',
    discount_value: 5,
    min_order_amount: 0,
    is_active: false,
    applies_to: 'all',
    catalog_scope: 'products',
    category_ids: [],
    service_ids: [],
    end_date: '2020-01-01',
  },
];
